<?php

declare(strict_types=1);

namespace LauLamanApps\DocumentSigner\Sdk\Placeholder;

use LauLamanApps\DocumentSigner\Sdk\Exception\PlaceholderException;
use LauLamanApps\DocumentSigner\Sdk\Field\FieldType;

final class PlaceholderParser
{
    /**
     * Recognises tokens of the form `{[type:signer:name]}` where each segment
     * is trimmed of surrounding whitespace. Whitespace inside segments is not allowed.
     *
     * The `{[` / `]}` delimiter pair is deliberately distinct from the `{{ }}` echo
     * syntax used by Blade, Twig, Vue and Mustache so the SDK input can be
     * generated by any of those engines without escaping.
     */
    private const PATTERN = '/\{\[\s*([A-Za-z]+)\s*:\s*([A-Za-z0-9_\-]+)\s*:\s*([A-Za-z0-9_\-]+)\s*\]\}/';

    /**
     * @return ParsedPlaceholder[]
     */
    public function parse(string $html): array
    {
        if (preg_match_all(self::PATTERN, $html, $matches, PREG_OFFSET_CAPTURE) === false) {
            throw new PlaceholderException('Failed to scan HTML for placeholders.');
        }

        $out = [];
        foreach ($matches[0] as $i => [$raw, $offset]) {
            $typeToken = $matches[1][$i][0];
            $signerKey = $matches[2][$i][0];
            $fieldName = $matches[3][$i][0];

            try {
                $type = FieldType::fromPlaceholderToken($typeToken);
            } catch (\ValueError $e) {
                throw new PlaceholderException(
                    "Unknown field type '{$typeToken}' in placeholder '{$raw}'.",
                    previous: $e,
                );
            }

            $out[] = new ParsedPlaceholder(
                raw: $raw,
                type: $type,
                signerKey: $signerKey,
                fieldName: $fieldName,
                byteOffset: $offset,
            );
        }

        return $out;
    }
}
